# Jekyll
markdown: redcarpet
permalink: /:categories/:title
pygments: true

baseurl: /chn

excerpt_separator: ""
comments: true


links:
  - title: About
    url: /chn/about/
  - title: Articles
    url: /chn/articles/
  - title: Blog
    url: /chn/
  - title: Category
    url: /chn/category/

# Personal
description: "Andy Lau / 刘松的博客"
ga_id: UA-49813880-1
name: Andy Lau
